databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgresql://mysite:s4UTkWZHjmB8xyGqKTUV8dpSfCDmsrsv@dpg-cqcmn02ju9rs739427n0-a/mysite_vpry
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: s4UTkWZHjmB8xyGqKTUV8dpSfCDmsrsv
        generateValue: true
      - key: s4UTkWZHjmB8xyGqKTUV8dpSfCDmsrsv
        value: 4