databases:
  - name: sorovnoma
    plan: free
    databaseName: sorovnoma
    user: sorovnoma_user

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgresql://sorovnoma_user:6v6viSkXcL6GEV0Q9CKnFCt6gtUr7QwD@dpg-cqct2e9u0jms73e4dag0-a.oregon-postgres.render.com/sorovnoma
        fromDatabase:
          name: sorovnoma
          property: connectionString
      - key: 6v6viSkXcL6GEV0Q9CKnFCt6gtUr7QwD
        generateValue: true
      - key: 6v6viSkXcL6GEV0Q9CKnFCt6gtUr7QwD
        value: 4