# Generated by Django 5.0.6 on 2024-07-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
        migrations.AddField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(to='backend.voter'),
        ),
    ]
