# Generated by Django 5.0.6 on 2024-07-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_question_voter_question_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.bot'),
            preserve_default=False,
        ),
    ]
