# Generated by Django 5.0.6 on 2024-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
