# Generated by Django 5.0.6 on 2024-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_voter_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required_channels',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
