# Generated by Django 5.0.6 on 2024-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required_channels',
            name='channel_link',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='required_channels',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
